### PR TITLE
feat(media observer): create media observer

### PR DESCRIPTION
**Pull request by samrichardsontylertech**
## PR Checklist

Please check if your PR fulfills the following requirements:

- Tests for the changes have been added: N
- Docs have been added / updated: N
- Does this PR introduce a breaking change? N
- I have linked any related GitHub issues to be closed when this PR is merged? N

## Describe the new behavior?
Added a media observer class to enable easy retrieval of browser preferences and capabilities like hover and prefers color scheme.

### CODE REVIEW

**Review by MikeMatusz — DISMISSED** [review]
I like how clean and familiar the subscription pattern looks.  If we find ourselves following this pattern more, the `MediaSubscriber` and `MediaSubscription` are generic enough you could pretty much just drop `Media` from the name and probably share some of the code for subscribe handling.

Curious to see the first examples of this in use, but looks like a nice clear API.  Though wouldn't hurt to throw some more JSDoc on the `MediaObserver` if that's the primary export that developers will be interacting with.

**Comment by samrichardsontylertech** [comment]
@MikeMatusz I'm worried that the way I'm handling subscriptions here is a poor substitute for actual RxJS. It works decently enough for this application, but if we want to expand on it maybe we should think about just adopting RxJS in this library and taking advantage of all their optimizations.

**Comment by MikeMatusz** [comment]
@samrichardsontylertech I'm a big fan of RxJS, and it's dead simple to use something like `fromEvent` or `fromCallback` to create a stream around something like this.  I've always assumed it would be a tough sell for inclusion, though, but maybe I'm wrong.  Angular developers are already using it, but I can't speak to the perspective of users of other frameworks.  Also due to the learning curve once you start chaining operators.

Something like this would probably be abstracted away most of the time from end applications, and really no one _has_ to do more than subscribe/unsubscribe, and it's very tree-shakeable.  I've also been keeping an eye on the [TC39 proposal for native observables](https://github.com/tc39/proposal-observable).  It's been in Stage 1 forever, but discussion has picked up again and I feel like it's starting to make some progress.  If it were ever implemented, RxJS would likely evolve into an extension library that mainly provides additional operators.

**Comment by samrichardsontylertech** [comment]
I generalized the observable classes from before so we can use them in other contexts. It's still not as good as real RxJS but handles this decently, avoids adding a dependency, and should be extensible enough if we need more features.

Everything else has been reimagined as a subclass of `Subject` with static members to track created observers and create new ones. Type safety is *completely* broken now but I'd really like to get that solid.

**Review by MikeMatusz — DISMISSED** [review]
This last commit definitely simplified things a bit to remove repeated similar code.  Definitely moves it a lot closer to RxJS as well.  I think if more things start using the `observable` implementation, we should consider using it. Things like `error`/`complete` support aren't as relevant here, but might for the next thing.

**Review by DRiFTy17 — DISMISSED** [review]

**Comment by samrichardsontylertech** [comment]
I updated the PR with comprehensive media feature support, some better typing, and separate factories for discrete, range, boolean, and custom queries.

**Comment by samrichardsontylertech** [comment]
Fixed a bug where a switch from one range query to the next (e.g. `(max-width: 599px)` to `(min-width: 600px)`) would cause the value to emit for each query with all but one value not matching the actual state.

**Review by DRiFTy17 — APPROVED** [review]

**Pull request merged**
